### ISSUE TITLE
Initials.py

### ISSUE THREAD

**Issue by ImprovementMajor** [ImprovementMajor/NewNew#2]
first_name=input("Please` enter your first name:")
middle_name=input("Please enter your middle name:")
last_name=input("Please enter your last name:")
full_name=(first_name[0], middle_name[0], last_name[:])
intials=input("Your full name is:")
print(full_name)

**Comment by bodrovis** [comment]
@ImprovementMajor You can ping me right here as you would do in any social network. All in all, this code is nice. Two things:

* There's no need to use `[:]` as you could have said `full_name=(first_name[0], middle_name[0], last_name[:])`
* Also I'm not sure what is the purpose of `intials=input("Your full name is:")`. This line is not needed because the user has already entered his/her name, middle name and surname previously.

**Comment by bodrovis** [comment]
And yeah, maybe it would be better to style the string a bit by adding dots:

```python
full_name=first_name[0] + '. ' +  middle_name[0] + '. ' + last_name
```

That would give you: `A. S. Pushkin`
