### ISSUE TITLE
GuessNumber.py

### ISSUE THREAD

**Issue by ImprovementMajor** [ImprovementMajor/NewNew#5]
@bodrovis Hi Ilya, can you please give me a little hint? Thank you
https://github.com/ImprovementMajor/NewNew/blob/4cdaa5b673617838fbb8683a56fe35e2ba8903f5/GuessNumber.py#L7

**Comment by bodrovis** [comment]
Hello @ImprovementMajor The problem is very trivial: you forgot to assign `input` to a variable in the following way:

```python
user_guess = input("Please enter your guess from 0 to 20...")
```

If you don't perform assignment, then when doing `int(user_guess)`, the `user_guess` variable will be effectively undefined, which leads to an error. Apart from that, I don't see any issues. Also, to practice a bit, I would recommend re-writing your conditions with if-elseif-else, instead of using nested if-else :)

**Comment by ImprovementMajor** [comment]
@bodrovis Thank you!
